version: "3.3"
services:

  db:
    image: postgres:16
    volumes:
      - ./db-pgdata:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    env_file:
      - .env
    ports:
      - "6543:5432"

  fake_smtp_server:
    image: gessnerfl/fake-smtp-server:2.1.3
    restart: always
    environment:
      - FAKESMTP_AUTHENTICATION_USERNAME=myuser
      - FAKESMTP_AUTHENTICATION_PASSWORD=mysecretpassword
    ports:
      - "8025:8025"      #expose smtp port
      - "8080:8080"      #expose web ui
      - "8081:8081"      #expose management api

  user_registration:
    image: "user_registration"
    depends_on:
      - db
    env_file:
      - .env
    build: .
    ports:
      - "9000:9000"

volumes:
  db-pgdata:
    driver: local
